import sys, os, json

comp_list = {}
trenders = []

days = ['#your dates in an array']
filename = '#your data directory/trender'
for day in days:
	filename_day = filename + str(day)
	f = open(filename_day, 'r')

	for line in f:
		symbol, score = line.split(', ')[0], line.split(', ')[1]
		
		symbol = symbol.strip("(")
		symbol = symbol.strip("'")
		score = score[:-2]

		if float(score) > 6 and symbol not in trenders:
			trenders.append(symbol)

	f.close()

print len(trenders)

for day in days:
	filename_day = filename + str(day)
	f = open(filename_day, 'r')

	for line in f:
		symbol, score = line.split(', ')[0], line.split(', ')[1]
		
		symbol = symbol.strip("(")
		symbol = symbol.strip("'")
		score = score[:-2]
		
		if symbol in trenders:
			if symbol not in comp_list:
				comp_list[symbol] = {}
				comp_list[symbol]['name'] = symbol
				comp_list[symbol]['sector'] = 'temp'
				comp_list[symbol]['trending'] = []

			comp_list[symbol]['trending'].append([day,float(score)])

	f.close()

filename2 = '$your quote directory, generated by Download.py'

prune = []

for entry in comp_list:

	first = 0
	last = 0
	for i in range(len(comp_list[entry]['trending'])):
		if 1105 in comp_list[entry]['trending'][i]:
			first = 1
		if 1116 in comp_list[entry]['trending'][i]:
			last = 1

	if first == 0:
		current_list = comp_list[entry]['trending']
		update = [[1105,0.0]]
		update = update + current_list
		comp_list[entry]['trending'] = update

	if last == 0:
		current_list = comp_list[entry]['trending']
		update = [[1129,0.0]]
		update = current_list + update
		comp_list[entry]['trending'] = update


	filename2_sym = filename2 + entry
	try:
		f = open(filename2_sym, 'r')

		content = f.read()
		if content.find('html') != -1:
			prune.append(entry)

		else:
			print entry
			for day in days:
				day_str = '2012-'+str(day)[:2]+'-'+str(day)[2:]
				k = content.find(day_str)
				if k != -1:
					j = content[k+1:].find('2012')
					if j != -1:
						i = content[k+j+2:].find('2012')
						if i != -1:
							newcontent = content[k:k+j]
							today_close = newcontent[newcontent.rfind(',')+1:]
							if today_close == "":
								today_close = '0.0'
							today_close = float(today_close)

							newcontent = newcontent[:newcontent.rfind(',')]
							vol = newcontent[newcontent.rfind(',')+1:]
							vol = float(vol)

							newcontent = content[k+j:k+j+i+1]
							prev_close = newcontent[newcontent.rfind(',')+1:]
							if prev_close == "":
								prev_close = '0.0'
							prev_close = float(prev_close)

							if prev_close == 0:
								prev_close = 1.0

							fluc = 100.0 * (today_close - prev_close) / prev_close

							if 'volume' not in comp_list[entry]:
								comp_list[entry]['volume'] = []
							if 'price_fluc' not in comp_list[entry]:
								comp_list[entry]['price_fluc'] = []

							comp_list[entry]['volume'].append([day,vol])
							comp_list[entry]['price_fluc'].append([day,fluc])

	except IOError as e:
		prune.append(entry)

for entry in comp_list:
	if 'volume' not in comp_list[entry]:
		prune.append(entry)
	if 'price_fluc' not in comp_list[entry]:
		prune.append(entry)
	if 'trending' not in comp_list[entry]:
		prune.append(entry)

for entry in prune:
	if entry in comp_list:
		del comp_list[entry]

# for entry in comp_list:
# 	if 'volume' not in comp_list[entry]:
# 		print entry
# 		print comp_list[entry]
# 	if 'price_fluc' not in comp_list[entry]:
# 		print entry
# 		print comp_list[entry]
# 	if 'trending' not in comp_list[entry]:
# 		print entry
# 		print comp_list[entry]

f = open('/Users/bjo/playground/Visualization/trending/data/stocks.json', 'w+')
f.write('[')
for entry in comp_list:
	f.write(json.dumps(comp_list[entry]))
	f.write(',')
f.write(']')
